# Generated by Django 5.1.3 on 2024-12-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_objectif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ponctuel',
        ),
    ]
