# Generated by Django 5.1.3 on 2024-12-02 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_ponctuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PonctualTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('coins_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('sub_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.submanager')),
            ],
        ),
    ]
