# Generated by Django 5.1.3 on 2024-12-13 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_ponctualtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='submanager',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submanager',
            name='yearly_objectif',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='submanager',
            name='monthly_objectif',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
