# Generated by Django 5.1.4 on 2025-04-15 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_submanager_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ponctualtask",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
